<?php
namespace config\table_helper;

class products {
    const TABLE_NAME = "products",
        ALL = self::TABLE_NAME.".*",
        ID = self::TABLE_NAME.".id",
        BRANCH_ID = self::TABLE_NAME.".branch_id",
        CODE = self::TABLE_NAME.".code",
        RANK = self::TABLE_NAME.".rank",
        CATEGORY_ID = self::TABLE_NAME.".category_id",
        IMAGE = self::TABLE_NAME.".image",
        CREATE_DATE = self::TABLE_NAME.".create_date",
        START_TIME = self::TABLE_NAME.".start_time",
        END_TIME = self::TABLE_NAME.".end_time",
        DELETE = self::TABLE_NAME.".is_delete",
        DELETE_DATE = self::TABLE_NAME.".delete_date",
        DELETE_IP = self::TABLE_NAME.".delete_ip",
        PRICE = self::TABLE_NAME.".price",
        PRICE_SAFE = self::TABLE_NAME.".price_safe",
        PRICE_TAKE_AWAY = self::TABLE_NAME.".price_take_away",
        PRICE_PERSONAL = self::TABLE_NAME.".price_personal",
        PRICE_COME_TAKE = self::TABLE_NAME.".price_come_take",
        PRICE_OTHER = self::TABLE_NAME.".price_other",
        VAT = self::TABLE_NAME.".vat",
        VAT_SAFE = self::TABLE_NAME.".vat_safe",
        VAT_TAKE_AWAY = self::TABLE_NAME.".vat_take_away",
        VAT_PERSONAL = self::TABLE_NAME.".vat_personal",
        VAT_COME_TAKE = self::TABLE_NAME.".vat_come_take",
        VAT_OTHER = self::TABLE_NAME.".vat_other",
        FAVORITE = self::TABLE_NAME.".favorite",
        ACTIVE_POS = self::TABLE_NAME.".active_pos",
        ACTIVE_MOBILE = self::TABLE_NAME.".active_mobile",
        ACTIVE_TAKE_AWAY = self::TABLE_NAME.".active_take_away",
        ACTIVE_COME_TAKE = self::TABLE_NAME.".active_come_take",
        NAME = self::TABLE_NAME.".name_",
        COMMENT = self::TABLE_NAME.".comment_",
        QUANTITY_ID = self::TABLE_NAME.".quantity_id";
}